<?php
/*
 * Moodle Gradetracker V1.0 – This code is copyright of Bedford College and is 
 * supplied for evaluation purposes only. The code may not be used for any 
 * purpose without permission from The Learning Technologies Team, 
 * Bedford College:  moodlegrades@bedford.ac.uk
 * 
 * Author mchaney@bedford.ac.uk
 */

/* List of events generated by the assign module, with the fields on the event object.
//http://docs.moodle.org/dev/Events_API#Triggering_an_event


//these are the assign assignment modules events! We can listen for 
//assessable_submitted. 
 * 
 * The events examples to trigger is:
 * 
 * $ue->enrolid      = $instance->id;
 $ue->status       = is_null($status) ? ENROL_USER_ACTIVE : $status;
 $ue->userid       = $userid;
 $ue->timestart    = $timestart;
 $ue->timeend      = $timeend;
 $ue->modifierid   = $USER->id;
 ...
 $ue->courseid  = $courseid;
 $ue->enrol     = $name;
 
 events_trigger('user_enrolled', $ue);
 * 
 * 
 * 
 * The events handling is: 
 * 
 * 
assessable_content_uploaded
    ->modulename     = 'assign';
    ->cmid           = // The cmid of the assign.
    ->itemid         = // The submission id of the user submission.
    ->courseid       = // The course id of the course the assign belongs to.
    ->userid         = // The user id that the attempt belongs to.
    ->content        = // The text content entered by the user (empty if no content submitted).
    ->pathnamehashes = // An array of pathnamehashes of the files submitted by the user (var not passed if not set).

assessable_file_uploaded
    ->modulename     = 'assign';
    ->cmid           = // The cmid of the assign.
    ->itemid         = // The submission id of the user submission.
    ->courseid       = // The course id of the course the assign belongs to.
    ->userid         = // The user id that the attempt belongs to.
    ->pathnamehashes = // An array of pathnamehashes of the files submitted by the user (var not passed if not set).

assessable_submitted
    ->modulename     = 'assign';
    ->cmid           = // The cmid of the assign.
    ->itemid         = // The submission id of the user submission.
    ->courseid       = // The course id of the course the assign belongs to.
    ->userid         = // The user id that the attempt belongs to.
    ->params         = // Array of module specific parameters.
        -> submission_editable = // Whether user can edit submission before assessment has been done.
*/


//THIS IS AN EXAMPLE:
$handlers = array (
    'user_enrolled' => array (
        'handlerfile'      => '/blocks/bcgt/lib.php',
        'handlerfunction'  => 'event_handle_user_enrolled',
        'schedule'         => 'cron',
        'internal'         => 1,
    ),
 
    'user_unenrolled' => array (
        'handlerfile'      => '/blocks/bcgt/lib.php',
        'handlerfunction'  => 'event_handle_user_unenrolled',
        'schedule'         => 'instant',
        'internal'         => 1,
    ),
);